### ISSUE TITLE
SpinKitView重复setIndeterminateDrawable后显示空白

### ISSUE THREAD

**Issue by start141** [ybq/Android-SpinKit#10]
在list页面复用（应该是重复setIndeterminateDrawable）SpinKitView时出现显示空白的现象。
如果是在xml里面指定好了Sprite（没有在代码里面重复setIndeterminateDrawable）则不会出现这样的问题

**Comment by start141** [comment]
![device-2016-04-12-181056](https://cloud.githubusercontent.com/assets/6055764/14457160/3823b1b6-00db-11e6-8e97-ca307c2bc7c6.png)

**Comment by ybq** [comment]
感谢您的反馈，应该是Drawable  Bounds的问题，周末会修复

**Comment by start141** [comment]
3Q
