### ISSUE TITLE
SpinKitView misbehaviour on Android 7

### ISSUE THREAD

**Issue by sealskej** [ybq/Android-SpinKit#19]
It seems `SpinKitView` doesn't work properly on Android 7, see videos.

**Android 6.0.1, Nexus 5**
![2016_09_06_11_45_26_11_53_15](https://cloud.githubusercontent.com/assets/550714/18269782/eee43800-7429-11e6-9423-941ded33b12f.gif)

**Android 7.0, Nexus 6P**
![2016_09_06_11_41_29_11_59_07](https://cloud.githubusercontent.com/assets/550714/18269786/f1d7bf32-7429-11e6-8b8e-7907d9329be3.gif)

**Comment by bubomancer** [comment]
I'm also experiencing the same issue.

**Comment by JaviChaques** [comment]
I have the same problem.

**Comment by ybq** [comment]
>the animator start delay should always be non-negative on N and above ...<a href='
https://developer.android.com/reference/android/animation/ValueAnimator.html#setStartDelay(long)'>
https://developer.android.com/reference/android/animation/ValueAnimator.html#setStartDelay(long)</a>
 
I'm looking for a suitable solution，If you have any idea，feel free to tell me
