### ISSUE TITLE
May I use this library for commercial purpose?

### ISSUE THREAD

**Issue by gcatak** [ybq/Android-SpinKit#29]
Hi, without any attribution or licence Can I use directly this library in my Android App?

**Comment by ybq** [comment]
This Library uses the MIT license

**Comment by gcatak** [comment]
I don't know licences. So can I use without any attribitiuon or licence?

**Comment by ybq** [comment]
https://en.wikipedia.org/wiki/MIT_License
 你去看看，我的英语不好
