### ISSUE TITLE
How to place a spinkit inside a button?

### ISSUE THREAD

**Issue by jairocgr** [ybq/Android-SpinKit#30]
The README's Preview section display a Button with a waved SpinKit within.

1. How can do that?
2. How can i put the SpinKit animation on the right band of the button?

**Comment by jairocgr** [comment]
I've found the answer on the [samples](https://github.com/ybq/Android-SpinKit/blob/master/sample/src/main/java/com/github/ybq/android/loading/Page2Fragment.java).

**Comment by ashish-patidar-rau** [comment]
> I've found the answer on the [samples](https://github.com/ybq/Android-SpinKit/blob/master/sample/src/main/java/com/github/ybq/android/loading/Page2Fragment.java).

Link is not working
