### ISSUE TITLE
Set Color Does Not Work On These Drawables

### ISSUE THREAD

**Issue by searchy2** [ybq/Android-SpinKit#37]
Set color via XML "app:SpinKit_Color="@color/colorAccent"" does not work on the following drawables:

- RotatingPlane
- Pulse
- RotatingCircle

For the above drawables, color defaults to white and setting color does not work. 

Set color via XML works for the following drawables:

- DoubleBounce
- Wave
- WanderingCubes
- ChasingDots
- ThreeBounce
- Circle
- CubeGrid
- FadingCircle
- FoldingCube

References Issue #24

**Comment by searchy2** [comment]
Thanks @firetrap for fixing this issue. Hope your PR is merged soon.

**Comment by searchy2** [comment]
Any update?

**Comment by omar-othmann** [comment]
Hi @searchy2 
it's work for me!

`xmlns:app="http://schemas.android.com/apk/res-auto"`
`app:SpinKit_Color="@color/colorAccent" `

`<com.github.ybq.android.spinkit.SpinKitView
            android:id="@+id/spin_kit"
            style="@style/SpinKitView.Large.Wave"
            android:layout_width="30dp"
            android:layout_height="30dp"
            android:layout_alignParentBottom="true"
            android:layout_alignParentLeft="true"
            android:layout_alignParentStart="true"
            android:layout_gravity="center"
            android:layout_marginLeft="44dp"
            android:layout_marginStart="44dp"
            app:SpinKit_Color="@color/colorAccent" />`

**Comment by searchy2** [comment]
Closing this issue for now.
