### ISSUE TITLE
Failed to resolve: com.github.ybq:Android-SpinKit:1.1.0

### ISSUE THREAD

**Issue by cagataykapuagasi** [ybq/Android-SpinKit#62]
build.gradle :
allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven { url "https://jitpack.io" }

    }
}

I tried everything and same issues but I had to open the issue.

**Comment by arshidkv12** [comment]
change android build grade in node_modules / android      compile 'com.github.ybq:Android-SpinKit:1.2.0'
