### ISSUE TITLE
Dependency implementation error!

### ISSUE THREAD

**Issue by geeky-auro** [ybq/Android-SpinKit#89]
When inserting in gradle dependencies it shows the following error..!
![image](https://user-images.githubusercontent.com/83534307/170034913-ca809d31-c192-422b-8d85-422aff9fa02b.png)

Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:debugRuntimeClasspath'.

**Comment by humaneBicycle** [comment]
download the code via zip. extract the file. 
1. In android studio go to File>import module>select library as destination.
2. remove the line "apply plugin: 'com.novoda.bintray-release" from build.gradle file in library folder.
3. add "implementation project(':library')" in app build.gradle files

**Comment by imafzalakram** [comment]
For folks using a recent Gradle version, add the jitpack repo in your settings.gradle file and the Spin Kit library should resolve and download.

   repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url 'https://jitpack.io' }
    }

**Comment by ApunichGULSHER** [comment]
> For folks using a recent Gradle version, add the jitpack repo in your settings.gradle file and the Spin Kit library should resolve and download.
> 
> repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS) repositories { maven { url 'https://jitpack.io' } }

Thanks, it works for me...
