### ISSUE TITLE
XML error

### ISSUE THREAD

**Issue by Tr-reny** [ybq/Android-SpinKit#90]
After syncing Dependency, the Build is successful, and Yet the XML code won't recognize the dependency.
Attached is the error on my XML
![Screenshot at 2022-08-27 12-06-46](https://user-images.githubusercontent.com/57016982/187038389-deab07bf-d4c8-4dd9-8520-89e6047f165c.png)

**Comment by EngZeeshanAli** [comment]
Did you find any solution?

**Comment by EngZeeshanAli** [comment]
@Tr-reny just add maven { url 'https://jitpack.io' }
Same like this in settings.gradle

```
dependencyResolutionManagement {
   repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
```


And this will start working reason is that this library is hosted on jitpack

**Comment by Tr-reny** [comment]
Thanks for the response.
Everything is working Perfectly Now

**Comment by Tr-reny** [comment]
@EngZeeshanAli 
Thanks
